on:
  pull_request:
    branches:
      - master

name: Benchmarks

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: ./.github/workflows/setup-rust
        with:
          cache: read

      - name: Benchmark
        run: |
          bash ./scripts/ci-run-benchmarks.sh . ${{ github.job }}

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: canbench_result_${{github.job}}
          path: /tmp/canbench_result_${{ github.job }}

      - name: Save PR number
        run: |
          echo ${{ github.event.number }} > /tmp/pr_number

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: pr_number
          path: /tmp/pr_number

      - name: Pass or fail
        run: |
          bash ./scripts/ci-post-run-benchmarks.sh
