on:
  workflow_run:
    workflows: ["Benchmarks"]
    types:
      - completed

name: Post Canbench results

jobs:
  download-results:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-benchmarks.outputs.matrix }}
      pr_number: ${{ steps.set-benchmarks.outputs.pr_number }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: dawidd6/action-download-artifact@80620a5d27ce0ae443b965134db88467fc607b43 # v7
        with:
          run_id: ${{ github.event.workflow_run.id }}

      - id: set-benchmarks
        run: bash ./scripts/ci-download-canbench-artifacts.sh

  post-comment:
    runs-on: ubuntu-latest
    needs: [download-results]
    strategy:
      matrix: ${{fromJSON(needs.download-results.outputs.matrix)}}
    steps:
      - name: Post comment
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          message: |
            ${{ matrix.benchmark.result }}
          comment-tag: ${{ matrix.benchmark.title }}
          pr-number: ${{ needs.download-results.outputs.pr_number }}

